#include <string.h>
#include <stdio.h>
#include <Ring_buffer.h>

// ─── Dataset ──────────────────────────────────────────────────────────────────
// Generated by Claude.ai
// Simulated UART byte stream: 10 temperature readings, ASCII encoded.
// Format: "T:XX.X\n" — exactly as a real sensor would send over serial.
 
char simulated_stream[] = {
    'T', ':', '2', '3', '.', '4', '\n',   // Reading 1
    'T', ':', '2', '3', '.', '7', '\n',   // Reading 2
    'T', ':', '2', '4', '.', '1', '\n',   // Reading 3
    'T', ':', '2', '4', '.', '0', '\n',   // Reading 4
    'T', ':', '2', '3', '.', '8', '\n',   // Reading 5
    'T', ':', '2', '5', '.', '2', '\n',   // Reading 6
    'T', ':', '2', '5', '.', '5', '\n',   // Reading 7
    'T', ':', '2', '5', '.', '1', '\n',   // Reading 8
    'T', ':', '2', '4', '.', '9', '\n',   // Reading 9
    'T', ':', '2', '4', '.', '6', '\n',   // Reading 10
};

//───────────────────────────────────────────────────────────────────────────────

/*
There are 3 possible scenarios for this ringbuffer
1)Normal: read and write
2)Slow: write then read
3)Random: mix of reading and writing
*/

//Handel the stream of reading comming in by storring them as strings
void store_stream(RingBuffer *rb) {
    static char message [16]; //size of message
    static char i = 0; //i = buffer index

    char c;
    while (rb_read(rb, &c)) {
        //if the value of c is the same as the one in the reading, delete it and increase the inded
        if (c == '/n') {
            message[i]= '/0'; //delete string
            i = 0; //reset index
            printf("stored reading: %s/n") //print value as string

        } else {
            message[i++]=c; //increase index

        }
    }
}

// Scenario 1: Normal
void scenario_normal (void){
    RingBuffer rb;
    rb_init(&rb);

    int total = sizeof(simulated_stream);
    for (int j = 0; j < total; j++) {
        rb_write(&rb, simulated_stream[j]);
        printf("#%d", j)

        //read every 7 bytes
        if ((j + 1) % 7 == 0 ) {
            process_buffer(&rb);

        }
    }
}


// Scenario 2: Slow
void scenario_slow (void){

}

// Scenario 3: Random
void scenario_random (void){

}


// Main loop
int main (void){
    printf("Ring Buffer/n");

    scenario_normal();
    scenario_slow();
    scenario_random();

}